# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=60, null=True, verbose_name='Author')),
                ('title', models.CharField(blank=True, max_length=80, null=True, verbose_name='Title')),
                ('date', models.DateField(auto_now=True, verbose_name='published')),
                ('time', models.TimeField()),
                ('content', models.TextField(blank=True, null=True, verbose_name='Article')),
            ],
            options={
                'verbose_name': 'ARTICLE',
                'verbose_name_plural': 'ARTICLES',
            },
        ),
    ]
